on:
  release:
    types: [published]

name: Release

permissions: {}
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        token: ${{ github.token }}
    - name: Set version variable
      id: version
      run: |
        echo "version=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
    - name: Set version and update release
      run: | 
        jq '.version = "${{ steps.version.outputs.version }}"' config.json > config.json.tmp
        mv config.json.tmp config.json
        echo -e "## ${{ steps.version.outputs.version }}\n- Updated to version [\`${{ steps.version.outputs.version }}\`](https://github.com/mrtncode/frametv-art-gallery/releases/tag/${{ steps.version.outputs.version }})\n" | cat - CHANGELOG.md > CHANGELOG.md.tmp
        mv CHANGELOG.md.tmp CHANGELOG.md
    - uses: stefanzweifel/git-auto-commit-action@fc84150d7c7500bbbaedb7ec522588fcc41f4d4d
      with:
        commit_message: "v${{ steps.version.outputs.version }}"